# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE      = attiny85
CLOCK      = 8000000
PROGRAMMER = -c usbtiny 
OBJECTS    = serkey.o uart_send.o
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES       = -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

# symbolic targets:
all:	serkey.hex

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:serkey.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID serkey.hex

clean:
	rm -f serkey.hex serkey.elf $(OBJECTS)

# file targets:
serkey.elf: $(OBJECTS)
	$(COMPILE) -o serkey.elf $(OBJECTS)

serkey.hex: serkey.elf
	rm -f serkey.hex
	avr-objcopy -j .text -j .data -O ihex serkey.elf serkey.hex
#	avr-size --format=avr --mcu=$(DEVICE) serkey.elf
	avr-size serkey.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	serkey.elf
	avr-objdump -d serkey.elf

cpp:
	$(COMPILE) -E serkey.c
